### ISSUE TITLE
switch to font coloring rather than background coloring

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/dump_r.php#50]
so this has bugged me for a long time.

the main reason for using (ugly) background colors rather than text colors is the inability to show leading/trailing whitespace for strings. this can be worked around in several ways.

already, an entirely empty string uses an gray "middle dot".

```css
/* display empty strings as a gray middle dot */
.dump_r .empty.string:not(.numeric) > .lbl .val:after {
	content: "\0387";
	color: #BBBBBB;
}
```
in addition, there is a trailing/leading right and left border that's added if the string is indicated as having leading/trailing spaces.

the key goal is to have the string copy-able to the clipboard in the exact form it was originally and that it be very obvious visually if there are trailing or leading spaces since they're frequently a huge source of time-consuming debugging for trivial reasons. one idea is just to render a color background only for leading/trailing spaces which means splitting them off into a separate div/span.

perhaps in combination with https://github.com/leeoniya/dump_r.php/issues/49, it should be possible to move the default theme away from using the jarring background colors, or at least provide a workable alternative with no sacrifices.
